export const COOKIES = {
  SELECTED_ROOM_ID: "HHC_SELECTED_ROOM_ID",
  SELECTED_ROOMS_IDS: "HHC_SELECTED_ROOMS_IDS",
  DEFAULT_SCENE_ID: "HCC_DEFAULT_SCENE_ID",
  HUE_BRIDGE_IP: "HUE_BRIDGE_IP",
  HUE_BRIDGE_USER: "HUE_BRIDGE_USER",
};

export const CONFIG_KEYS = {
  DEFAULT_PAGE_TYPE: "DEFAULT_PAGE_TYPE",
  ACTION_TRIGGER_SENSOR_NAME: "ACTION_TRIGGER_SENSOR_NAME",
  SOUNDS_ON: "SOUNDS_ON",
  SCREENSAVER_ON: "SCREENSAVER_ON",
  SHOULD_SHOW_ROOM_LABEL_ON_SWITCH: "SHOULD_SHOW_ROOM_LABEL_ON_SWITCH",
};
