export const COOKIES = {
  SELECTED_ROOM_ID: "HHC_SELECTED_ROOM_ID",
  SELECTED_ROOMS_IDS: "HHC_SELECTED_ROOMS_IDS",
  DEFAULT_SCENE_ID: "HCC_DEFAULT_SCENE_ID",
  HUE_BRIDGE_IP: "HUE_BRIDGE_IP",
  HUE_BRIDGE_USER: "HUE_BRIDGE_USER",
  CONFIG_DEFAULT_PAGE_TYPE: "CONFIG_DEFAULT_PAGE_TYPE",
  CONFIG_ACTION_TRIGGER_SENSOR_NAME: "CONFIG_ACTION_TRIGGER_SENSOR_NAME",
  CONFIG_SOUNDS_ON: "CONFIG_SOUNDS_ON",
  CONFIG_SCREENSAVER_ON: "CONFIG_SCREENSAVER_ON",
};
